version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@hapi/hapi"
    versions:
    - 20.1.0
    - 20.1.1
  - dependency-name: exceljs
    versions:
    - 4.2.1
  - dependency-name: joi
    versions:
    - 17.4.0
  - dependency-name: "@hapi/hoek"
    versions:
    - 9.1.1
  - dependency-name: fast-csv
    versions:
    - 4.3.6
